//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TektonChallengeProducts.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TektonChallengeProducts.Application.Resources.ValidationMessagesResources", typeof(ValidationMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is mandatory..
        /// </summary>
        public static string DescriptionMandatory {
            get {
                return ResourceManager.GetString("DescriptionMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot exceed {MaxLength} characters..
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id is invalid or missing..
        /// </summary>
        public static string InvalidOrMissingId {
            get {
                return ResourceManager.GetString("InvalidOrMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is mandatory..
        /// </summary>
        public static string NameMandatory {
            get {
                return ResourceManager.GetString("NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot exceed {MaxLength} characters..
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price must be greater than zero..
        /// </summary>
        public static string PriceGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status dictionary not found in cache..
        /// </summary>
        public static string StatusDictionaryNotCached {
            get {
                return ResourceManager.GetString("StatusDictionaryNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;{0}&apos; not found in cache..
        /// </summary>
        public static string StatusNotFoundInCache {
            get {
                return ResourceManager.GetString("StatusNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stock cannot be negative..
        /// </summary>
        public static string StockCantBeNegative {
            get {
                return ResourceManager.GetString("StockCantBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors.
        /// </summary>
        public static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
    }
}
